_base_: [cfgs/infer/text2img.yaml]

clip_skip: 1 #动漫模型通常会跳过一个CLIP层

new_components:
  scheduler:
    _target_: diffusers.EulerAncestralDiscreteScheduler # change Sampler
    beta_start: 0.00085
    beta_end: 0.012
    beta_schedule: 'scaled_linear'